receivers:
  simpleprometheusremotewrite:
    Timeout: 100
    ListenPath: "/metrics"
    ListenAddr:
      Endpoint: "localhost:8888"
      Transport: "tcp"
extensions:
    health_check:
      endpoint: 0.0.0.0:13133
processors:
  batch:
exporters:
  signalfx:
    # to configure, see https://github:com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter
    access_token: ${SPLUNK_ACCESS_TOKEN}
    realm: "${SPLUNK_REALM}"
  logging:
    loglevel: debug
service:
  telemetry:
    metrics:
      address: ":8888"
  pipelines:
#    metrics/sfx:
#      receivers: [simpleprometheusremotewrite]
#      processors: [batch]
#      exporters: [signalfx]
    metrics/logging:
      receivers: [simpleprometheusremotewrite]
      processors: [batch]
      exporters: [logging]
