receivers:
  simpleprometheusremotewrite:
    endpoint: "0.0.0.0:54090"
    transport: "tcp"
    path: "/metrics"
    timeout_seconds: 100000000
    buffer_size: 100
extensions:
    health_check:
      endpoint: 0.0.0.0:8888
processors:
  batch:
exporters:
  signalfx:
    # to configure, see https://github:com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    realm: "${SPLUNK_REALM}"
  logging:
    loglevel: debug
service:
  telemetry:
    metrics:
      address: ":54090"
  pipelines:
#    metrics/sfx:
#      receivers: [simpleprometheusremotewrite]
#      processors: [batch]
#      exporters: [signalfx]
    metrics/logging:
      receivers: [simpleprometheusremotewrite]
      processors: [batch]
      exporters: [logging]
