name: actions-test-playground

on:
  push:
    branches:
      - 'test_actions*'
  pull_request:
    paths:
      - '.github/workflows/actions-test-playground.yml'
      - 'internal/buildscripts/packaging/temp-gh-actions-test/**'
      - 'Makefile'

concurrency:
  group: actions-test-playground-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'
  PIP_VERSION: '22.0.4'
  GO_VERSION: 1.19.0

jobs:
  setup-environment:
    name: setup-environment
    # Use 20.04.5 until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16450 is resolved
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Test env vars
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "GITHUB_REF_NAME=$GITHUF_REF_NAME"
          echo "REF_TYPE=$REF_TYPE"
          make install-tools
          make test-gh-actions
